config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users do
  resource :profile
  end

  resources :users, only: [:tab] do
   member do
    get 'tab'
    end
    end
   
   
 

  resources :users, only: [:index]
    
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :restore
    end
  end   

  resources :conversations, only: [:index, :show, :destroy] do
    collection do
      delete :empty_trash
    end
  end

  resources :conversations, only: [:index, :show, :destroy] do
    member do
     post :mark_as_read
    end
  end  
  
  resources :messages, only: [:new, :create] 

  resources :posts do
    resources :comments 
  end
  resources :tags, only: [:index, :show] 
  resources :papers
  resources :cleanings
  resources :electros
  resources :hwaters
  resources :transports
  resources :garbages
  resources :friendships
  resources :addons
  root 'pages#index'

  

 
  get 'about' => 'pages#about'
  get 'gb' => 'pages#gb_index'
 
  get 'compare_friends', to: 'users#compare' 
  get 'add_friend', to: 'users#add_friend'

end

app/models/user.rb
class User < ActiveRecord::Base
	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
has_many :papers 
has_many :cleanings
has_many :electros
has_many :hwaters
has_many :transports
has_many :garbages

has_many :pages

has_many :friendships, dependent: :destroy
has_many :friends, through: :friendships
has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
has_many :inverse_friends, through: :inverse_friendships, :source => :user

has_many :posts
has_many :comments

has_many :addons

has_one :profile
accepts_nested_attributes_for :profile

acts_as_messageable

	def average_paper_types
  		self.papers.group(:paper_type).sum(:paper_weight)
	end

	def average_transport_types
  		self.transports.group(:transport_type).sum(:transport_km) 
	end


	def mailboxer_email(object)
		object.email
	end

	#def not_friends_with?(friend_id)
		#friendships.where(friend_id: friend_id).count < 1

	#end

	#def except_current_user(users)
	#	users.reject { |user| user.id == self.id }
	#end

	#def self.search(param)
		#return User.none if param.blank?

		#param.strip!
		#param.downcase!
		#(name_matches(param) + email_matches(param)).uniq
	#end
	
	#def self.name_matches(param)
	#	matches('name', param)
	#end

	#def self.email_matches(param)
	#	matches('email', param)
	#end	
#
	#def self.matches(field_name, param)
		#where("lower(#{field_name}) like ?", "%#{param}%")
	#end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  
  

	def index
		@users = User.all
    @users = User.order('created_at DESC').paginate(page: params[:page], per_page: 30)

    
	end



    def create
   
    end


	def show
   # @user = current_user
		@user = User.find(params[:id])
	  @users = User.order('created_at DESC').paginate(page: params[:page], per_page: 30)
    @users_buisness_type = User.where(:buisness_type => current_user.profile.buisness_type).order('created_at DESC').paginate(page: params[:page], per_page: 30)
    #@electro_total = current_user.electros.sum(:electricity_kwst) 
    @paper = current_user.papers.build
    @electro = current_user.electros.build
    @hwater = current_user.hwaters.build
    @cleaning = current_user.cleanings.build
    @transport = current_user.transports.build

    @papers = current_user.papers

    @addon = current_user.addons.build
    #@addons = current_user.addons
    

	end

	def compare
		if current_user.profile
		#@user = User.find(params[:id])
		#@#users = User.friendships.friend(params[:id])
    @user = User.find_by(id: params[:to].to_i) if params[:to]

		@paper_weight_total_user = @user.papers.sum(:paper_weight) 
		@paper_weight_per_capita_user = @user.papers.sum(:paper_weight) / (@user.profile.staff) 
		@env_paper_weight_user = @user.papers.sum(:env_paper_weight)
		@env_paper_ratio_user = (@env_paper_weight_user / @paper_weight_total_user) * 100	

		@paper_tree_ratio_user = (@user.papers.sum(:paper_weight) / 1000) *15 
    	@paper_tree_co2_rescue_user = @paper_tree_ratio_user * (0.492)

    	#Rafmagn  
    	   @electro_total_user = @user.electros.sum(:electricity_kwst)
           @electro_total_per_capita_user = @user.electros.sum(:electricity_kwst) / @user.profile.staff 
           @electro_total_per_m2_user = @user.electros.sum(:electricity_kwst) / @user.profile.building_size
        #HotWater    
          @hwater_total_m3_user = @user.hwaters.sum(:hot_water_cubic_meter) 
           @hwater_total_m3_per_capita_user = @user.hwaters.sum(:hot_water_cubic_meter) /@user.profile.staff
           @hwater_m3_m2_ratio_user = @user.hwaters.sum(:hot_water_cubic_meter) / @user.profile.building_size   

        #Ræsting
           @cleaning_total_user = @user.cleanings.sum(:cleaning_liter)
           @cleaning_staff_ratio_user = @user.cleanings.sum(:cleaning_liter) / @user.profile.staff
           @cleaning_building_ratio_user = @user.cleanings.sum(:cleaning_liter) / @user.profile.building_size   

        #Ferðalog-bilar
           @transport_co2_km_user = @user.transports.sum(:transport_km) * (0.1404)
           @transport_co2_km_staff_ratio_user = @user.transports.sum(:transport_km) * (0.1404) / @user.profile.staff
           @transport_km_staff_ratio_user = @user.transports.sum(:transport_km) / @user.profile.staff
           @transport_km_user = @user.transports.sum(:transport_km)
        #Ferðalog-flug
          @transport_flight_co2_user = @user.transports.sum(:transport_flight_km) * (0.1722)   
          @transport_flight_co2_staff_ratio_user = @user.transports.sum(:transport_flight_km) * (0.1722) / @user.profile.staff
          @transport_flight_km_user = @user.transports.sum(:transport_flight_km) 
          @transport_flight_km_staff_ratio_user = @user.transports.sum(:transport_flight_km) / @user.profile.staff

        #Co2 vegna ferðalaga
          @co2_due_to_transport_user = (@transport_flight_co2 + @transport_co2_km) / 1000

          @tree_count_rescue_user = @co2_due_to_transport * 492    
	else
		redirect_to user_path
	end
	end

 


end

app/helpers/users_helper.rb
module UsersHelper

	

	def webpage_title_helper
		"<i class='fa fa-code'></i>".html_safe
	end	
end

app/views/users/shared/_cleaning_compare.html.erb
<% if current_user.profile %>

<div class="col-md-8 col-md-offset-1 well">
<h3>Samburður Hreinsiefni</h3>
		<div class="col-md-6">

			<table class="table table-hover table-box-compare ">
				<thead>
					<th>Samburður - Hreinsiefni</th>
					<th><%= @user.profile.name %></th>
					<th><%= current_user.profile.name %></th><br>
				</thead>
				<tbody>
					<tr>
						<td>Heildar Hreinsiefni Lítrar</td>
						<td><strong><%= @cleaning_total_user %> l </strong></td>
						<td><strong><%= @cleaning_total %> l </strong></td>
					</tr>
				   <tr>
						<td>Lítrar hreinsiefni á hvert stöðugildi</td>
						<td> <strong><%=  @cleaning_staff_ratio_user %> -l/stg </strong></td>
						<td><strong><%=  @cleaning_staff_ratio %> -l/stg </strong></td>
				   </tr>	
						<br>
					<tr>
						<td> lítrar á hvern m&sup2;</td>
						<td> <strong><%= @cleaning_building_ratio_user %> l/m&sup2; </strong></td>
						<td> <strong><%= @cleaning_building_ratio %> l/m&sup2; </strong></td>
					</tr>
					
					
				</tbody>
			</table>	
		</div>

		<div class="col-md-6">
		Hreinsiefni Samanburður við <%= @user.profile.name %>
		 					<%= line_chart [
  								{name: "Hreinsiefni -L.", data: current_user.cleanings.map{|t| [t.date, t.cleaning_liter] }, 'interpolateNulls':true},
  								{name: "Umhverfiv. Hreinsiefni -L.", data: current_user.cleanings.map{|t| [t.date, t.env_clean_ratio] }, 'interpolateNulls':true},
  								{name: "Hreinsiefni -L.", data: @user.cleanings.map{|t| [t.date, t.cleaning_liter] }, 'interpolateNulls':true},
  								{name: "Umhverfisv. Hreinsiefni -L.", data: @user.cleanings.map{|t| [t.date, t.env_clean_ratio] }, 'interpolateNulls':true} ] %>
  				
		</div>
</div>		

<p>Create your profile so that you can share your info and follow other users. </p>
            <%= link_to " Create your profile", new_user_profile_path(current_user), class: 'btn-primary btn-lg btn-block' %>
          <% end %>

app/views/users/shared/_compare_users.html.erb
<div class="row">

	

	
	<%= render 'users/shared/paper_compare' %>
	

	<%= render 'users/shared/electro_compare' %>	 

	<%= render 'users/shared/hwater_compare' %>	 

	<%= render 'users/shared/cleaning_compare'	%>

	<%= render 'users/shared/travel_compare'	%>
	
		
	
	
 
</div> 

app/views/users/shared/_electro_compare.html.erb
<% if current_user.profile %>

<div class="col-md-8 col-md-offset-1 well">
<h3>Samburður Rafmagn</h3>
		<div class="col-md-6">

			<table class="table table-hover table-box-compare ">
				<thead>
					<th>Samburður - Rafmagn</th>
					<th><%= @user.profile.name %></th>
					<th><%= current_user.profile.name %></th><br>
				</thead>
				<tbody>
					<tr>
						<td>heildar rafmagnsnotkun</td>
						<td><strong><%= @electro_total_user %> kwst </strong></td>
						<td><strong><%= @electro_total %> kwst </strong></td>
					</tr>
				   <tr>
						<td>kwst á hvert stöðugildi</td>
						<td> <strong><%= @electro_total_per_capita_user %> kwst </strong></td>
						<td><strong><%= @electro_total_per_capita %> kwst </strong></td>
				   </tr>	
						<br>
					<tr>
						<td> kwst. f hvert stöðugildi</td>
						<td> <strong><%= @electro_total_per_m2_user %> kwst/fm. </strong></td>
						<td> <strong><%= @electro_total_per_m2 %> kwst/fm. </strong></td>
					</tr>
					
					
				</tbody>
			</table>	
		</div>

		<div class="col-md-6">
		Rafmagnsnotkun Samanburður við <%= @user.profile.name %>
		 					<%= bar_chart [
  								{name: "Rafmagnsnotkun #{@user.profile.name}", data: @electro_total_user, 'interpolateNulls':true},
  								{name: "Rafmagn á hvert stöðugildi #{@user.profile.name}", data: @electro_total_per_capita_user, 'interpolateNulls':true},
  								{name: "Rafmagnsnotkun #{current_user.profile.name}", data: @electro_total, 'interpolateNulls':true},
  								{name: "Rafmagn á hvert stöðugildi #{current_user.profile.name}", data: @electro_total_per_capita, 'interpolateNulls':true} ] %>
		</div>
</div>	


          <% end %>	

app/views/users/shared/_friends.html.erb
<!--<h3> Vinir mínir </h3>
             <ul>
               <#% for friendship in @user.friendships %>
               <li>
               <%#= friendship.friend.profile.name %>
               (<%#= link_to "Eyða vinskap", friendship, :method => :delete %>)
               </li>
              <%# end %>
             </ul> 

             <p> <%#= link_to "Finna vini", users_path %> </p>

             <h3> þeir sem elta mig </h3>
             <ul>
             	<%# for user in @user.inverse_friends %>
             	<li><%#= user.profile.name %></li>
             	<%# end%>
             	</ul>-->



<h5> <%= current_user.profile.name%> eltir:</h5>
             <ul>
               <% @user.friendships.each do |friendship| %>
               <li>
                <%= link_to user_profile_path(friendship.friend), :method => :get do %>
                  <%= friendship.friend.profile.name %>
                  (<%= link_to "Eyða vináttu", friendship, :method => :delete %>)
                  <%= link_to friendship do %>
            
                  <%= link_to 'Senda Skilaboð', new_message_path(to: friendship.friend.id) %> 

                  <%= link_to friendship do %>

                  <%= link_to 'Bera saman', compare_friends_path(to: friendship.friend.id)%>
                  <% end %>
              <% end %>
              <% end %>
              <% end %>
              
            </li>
             </ul> 

             <p> <%= link_to "Finna vini", users_path %> </p>

             
              <h5> þeir sem elta <%= current_user.profile.name%> </h5>
             <ul>
              <%  @user.inverse_friends.each do |user| %>
              <%= link_to user_profile_path(user), :method => :get do %>
                <li><%= user.profile.name %></li>
              <% end%>
              <% end %>
              </ul>
              

app/views/users/shared/_hwater_compare.html.erb
<% if current_user.profile %>

<div class="col-md-8 col-md-offset-1 well">
<h3>Samburður Heitt vatn</h3>
		<div class="col-md-6">

			<table class="table table-hover table-box-compare ">
				<thead>
					<th>Samburður - Heitt Vatn</th>
					<th><%= @user.profile.name %></th>
					<th><%= current_user.profile.name %></th><br>
				</thead>
				<tbody>
					<tr>
						<td>heildar heita vatns notkun m&#179;</td>
						<td><strong><%= @hwater_total_m3_user %> m&#179; </strong></td>
						<td><strong><%= @hwater_total_m3 %> m&#179; </strong></td>
					</tr>
				   <tr>
						<td>m&#179; á hvert stöðugildi</td>
						<td> <strong><%= @hwater_total_m3_per_capita_user %> m&#179;/stg </strong></td>
						<td><strong><%= @hwater_total_m3_per_capita %> m&#179;/stg </strong></td>
				   </tr>	
						<br>
					<tr>
						<td> m&#179; á hvern m&sup2;</td>
						<td> <strong><%= @hwater_m3_m2_ratio_user %> m&#179;/m&sup2; </strong></td>
						<td> <strong><%= @hwater_m3_m2_ratio %> m&#179;/m&sup2; </strong></td>
					</tr>
					
					
				</tbody>
			</table>	
		</div>

		<div class="col-md-6">
		Rafmagnsnotkun Samanburður við <%= @user.profile.name %>
		 					<%= column_chart [
  								{name: "Heitavatns notkun #{@user.profile.name}", data: @hwater_total_m3_user.to_i, 'interpolateNulls':true},
  								{name: "heitt vatn á stöðugildi #{@user.profile.name}", data: @hwater_total_m3_per_capita_user.to_i , 'interpolateNulls':true},
  								{name: "Heitavatns notkun#{current_user.profile.name}", data: @hwater_total_m3.to_i, 'interpolateNulls':true},
  								{name: "Heitt vatn á hvert stöðugildi #{current_user.profile.name}", data: @hwater_total_m3_per_capita.to_i, 'interpolateNulls':true} ] %>
		</div>
</div>	

<p>Create your profile so that you can share your info and follow other users. </p>
            <%= link_to " Create your profile", new_user_profile_path(current_user), class: 'btn-primary btn-lg btn-block' %>
          <% end %>	

app/views/users/shared/_travel_compare.html.erb
<% if current_user.profile %>

<div class="col-md-8 col-md-offset-1 well">
<h3>Samburður Ferðir</h3>
		<div class="col-md-6">

			<table class="table table-hover table-box-compare ">
				<thead>
					<th>Samburður - Bílferðir</th>
					<th><%= @user.profile.name %></th>
					<th><%= current_user.profile.name %></th><br>
				</thead>
				<tbody>
					<tr>
						<td>Heildar km í bílferðir</td>
						<td><strong><%= @transport_km_user %> km </strong></td>
						<td><strong><%= @transport_km %> km </strong></td>
					</tr>
				   <tr>
						<td>Km f. hvert stöðugildi</td>
						<td> <strong><%=  @transport_km_staff_ratio_user %> km </strong></td>
						<td><strong><%=  @transport_km_staff_ratio %> km </strong></td>
				   </tr>	
						<br>
					<tr>
						<td> Heildar losun co2 v. ferða</td>
						<td> <strong><%=  @transport_co2_km_user %> kg/co2 </strong></td>
						<td> <strong><%=  @transport_co2_km %> kg/co2 </strong></td>
					</tr>

					<tr>
						<td>Losun co2 f. hvert stöðugildi</td>
						<td> <strong><%=  @transport_co2_km_staff_ratio_user %> kg/co2 </strong></td>
						<td> <strong><%=  @transport_co2_km_staff_ratio %> kg/co2 </strong></td>
					</tr>
					
					
				</tbody>
			</table>	
		</div>

		<div class="col-md-6">
		Bílferðir Samanburður við <%= @user.profile.name %>
		 					<%#= line_chart [
  								{name: "losun co2 vegna bílferða #{current_user.profile.name}", data: current_user.transports.map{|t| [t.date, t.transport_km * (0.1404)] }, 'interpolateNulls':true},
  								
  								{name: "losun co2 vegna bílferða #{@user.profile.name}", data: @user.transports.map{|t| [t.date, t.transport_km * (0.1404)] }, 'interpolateNulls':true} ] %>
  				
		</div>

		<div class="col-md-6">

			<table class="table table-hover table-box-compare ">
				<thead>
					<th>Samburður - Flug</th>
					<th><%= @user.profile.name %></th>
					<th><%= current_user.profile.name %></th><br>
				</thead>
				<tbody>
					<tr>
						<td>Heildar km fjöldi flugferða</td>
						<td><strong><%= @transport_flight_km_user %> km </strong></td>
						<td><strong><%= @transport_flight_km %> km </strong></td>
					</tr>
				   <tr>
						<td> Km fjöldi flugferðir f. hvert stöðugildi</td>
						<td> <strong><%= @transport_flight_co2_staff_ratio_user %> km </strong></td>
						<td><strong><%=  @transport_flight_co2_staff_ratio %> km </strong></td>
				   </tr>	
						<br>
					<tr>
						<td> Heildar losun co2 v. flugferða</td>
						<td> <strong><%=  @transport_flight_co2_user %> kg/co2 </strong></td>
						<td> <strong><%=  @transport_flight_co2 %> kg/co2 </strong></td>
					</tr>

					<tr>
						<td>Losun co2 f. hvert stöðugildi v. flugferða</td>
						<td> <strong><%=  @transport_flight_co2_staff_ratio_user %> kg/co2 </strong></td>
						<td> <strong><%=  @transport_flight_co2_staff_ratio %> kg/co2 </strong></td>
					</tr>
					
					
				</tbody>
			</table>	
		</div>

		<div class="col-md-6">
		Flugferðir Samanburður við <%= @user.profile.name %>
		 					<%#= line_chart [
  								{name: "losun co2 vegna flugferða #{current_user.profile.name}", data: current_user.transports.map{|t| [t.date, t.transport_km * (0.1722)  ] }, 'interpolateNulls':true},
  								
  								{name: "losun co2 vegna flugferða #{@user.profile.name}", data: @user.transports.map{|t| [t.date, t.transport_flight_km * (0.1722)  ] }, 'interpolateNulls':true} ] %>
  				
		</div>
</div>		

<p>Create your profile so that you can share your info and follow other users. </p>
            <%= link_to " Create your profile", new_user_profile_path(current_user), class: 'btn-primary btn-lg btn-block' %>
          <% end %>

app/views/users/shared/_user_total.html.erb
 <% if current_user.profile %>


		<div class="col-md-6" id="pappir">	
			<div class="panel panel-default">
  				<div class="panel-heading">
    				<h3 class="panel-title"> 
    				<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne"><span class="glyphicon glyphicon-minus"></span><%= current_user.name %>: Pappírs notkun</a> <%= link_to "Skrá Pappír", user_path(current_user), class: 'pull-right ' %></h3>
  				</div>
  				    <div id="collapseOne" class="panel-collapse collapse in">

 			 <div class="panel-body">
				
         <% if current_user.profile %>
					<%= render 'pages/partials/paper_part' %>
				<% end %>
			</div>	
			</div>	
		</div>	
   </div> 
</div>
 
  <div class="col-md-6 pull-right" id="electro">  
		<div class="panel panel-default">
  			<div class="panel-heading">
    			<h3 class="panel-title"> 
    				<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo"><span class="glyphicon glyphicon-plus"></span><%= current_user.name %>: Rafmagns notkun</a><%= link_to "Skrá Rafmagn", electros_path, class: 'pull-right ' %></h3>
  			</div>
  			    <div id="collapseTwo" class="panel-collapse collapse">

 			 <div class="panel-body">
			
				
				<%= render 'pages/partials/electro_part' %>
						
         			
         		</div>
    		</div>  		 
		</div>
   </div> 


<!-- Heitt vatn Panel byrjar -->


  <div class="col-md-6" id="Hwater">  
		<div class="panel panel-default">
  			<div class="panel-heading">
    			<h3 class="panel-title"><a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
          <span class="glyphicon glyphicon-plus"></span><%= current_user.name %>: Heit Vatn Notkun</a><%= link_to "Skrá Heitt vatn", hwaters_path, class: 'pull-right ' %></h3>
  			</div>
  			 <div id="collapseThree" class="panel-collapse collapse">
 			 	<div class="panel-body">
			
					
					<%= render 'pages/partials/hwater_part' %>
         
         	</div>		
    		</div>  		 
		</div>
  </div>

		<!-- Heitt vatn Panel Endar -->

		<!-- HreingerningarEfni Panel byrjar -->
   
  <div class="col-md-6 pull-right">    
		<div class="panel panel-default">
  			<div class="panel-heading">
    			<h3 class="panel-title"><a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseFour">
          <span class="glyphicon glyphicon-plus"></span><%= current_user.name %>: Notkun Ræstiefna</a><%= link_to "Skrá Ræstiefni", cleanings_path, class: 'pull-right ' %></h3>
  			</div>
  			 <div id="collapseFour" class="panel-collapse collapse">
 			 	<div class="panel-body">
			
					
					<%= render 'pages/partials/cleaning_part' %>
         		
         	</div>		
    		</div>  		 
		</div>
  </div> 
 

		<!-- Hreingerningarefni Panel Endar -->

		<!-- Ferðalög Panel byrjar -->

  <div class="col-md-6">    
		<div class="panel panel-default">
  			<div class="panel-heading">
    			<h3 class="panel-title"><a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseFive">
          <span class="glyphicon glyphicon-plus"></span><%= current_user.name %>: Flug og Ferðir</a><%= link_to "Skrá Ferðir", transports_path, class: 'pull-right ' %></h3>
  			</div>
  			 <div id="collapseFive" class="panel-collapse collapse">
 			 	<div class="panel-body">
			
				
					<%= render 'pages/partials/travel_part' %>
         		</div>
         	</div>		
    		</div>  		 
		</div>
		<!-- Ferðir Panel Endar -->
	 <!-- Panel body end -->
<!--Col Ends -->

 <!-- row ends -->
<% else %>

          <p>Create your profile so that you can share your info and follow other users. </p>
            <%= link_to " Create your profile", new_user_profile_path(current_user), class: 'btn-primary btn-lg btn-block' %>
          <% end %>

<script type="text/javascript">
	$('.collapse').on('shown.bs.collapse', function(){
$(this).parent().find(".glyphicon-plus").removeClass("glyphicon-plus").addClass("glyphicon-minus");
}).on('hidden.bs.collapse', function(){
$(this).parent().find(".glyphicon-minus").removeClass("glyphicon-minus").addClass("glyphicon-plus");
});
</script>

app/views/users/shared/_users_find.html.erb
<div class="row">

	<div class="col-md-8 col-md-offset-2">
		<ul class="list-unstyled">
		<% @users.each do |user| %>
		
			<% if user.profile %>
			<li>
				<div class="well row <%= cycle("white-bg", '') %>">
				  <% unless current_user == user %>
					<div>
					
						<%= link_to user do %>
						<h2><%= user.profile.name %></h2>
						
						<%= link_to "Gerast vinur", friendships_path(:friend_id => user), :method => :post %>
						 <%= link_to 'Send message', new_message_path(to: user.id), class: 'btn btn-default btn-sm' %>
						 <p><%= user.profile.description %></p>
						<% end %>
						
						
					</div>
				  <% end %>	
				</div>	
			</li>
		<% end %>
		<% end %>
		</ul>
	</div>
</div>

<ul>
  <% @users.each do |user| %>
    <li>
      <strong><%= user.name %></strong>
      <% unless current_user == user %>
        <%= link_to 'Send message', new_message_path(to: user.id), class: 'btn btn-default btn-sm' %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>