config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users do
  resource :profile
  end

  resources :users, only: [:tab] do
   member do
    get 'tab'
    end
    end
   
   
 

  resources :users, only: [:index]
    
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :restore
    end
  end   

  resources :conversations, only: [:index, :show, :destroy] do
    collection do
      delete :empty_trash
    end
  end

  resources :conversations, only: [:index, :show, :destroy] do
    member do
     post :mark_as_read
    end
  end  
  
  resources :messages, only: [:new, :create] 

  resources :posts do
    resources :comments 
  end
  resources :tags, only: [:index, :show] 
  resources :papers
  resources :cleanings
  resources :electros
  resources :hwaters
  resources :transports
  resources :garbages
  resources :friendships
  resources :addons
  root 'pages#index'

  

 
  get 'about' => 'pages#about'
  get 'gb' => 'pages#gb_index'
 
  get 'compare_friends', to: 'users#compare' 
  get 'add_friend', to: 'users#add_friend'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  has_many :taggings 
  has_many :tags, through: :taggings

  def self.tagged_with(name)
    ids = Tagging.where(taggable_type: self.name)
            .joins(:tag)
            .where(tags: {name: name}).pluck(:taggable_id)
    find(ids)
  end

  def self.tag_counts
    Tag.select("tags.id, tags.name,count(taggings.tag_id) as count").
      joins(:taggings).group("taggings.tag_id, tags.id, tags.name")
  end

  def tag_list
    tags.map(&:name).join(", ")
  end

  def tag_list=(names)
    self.tags = names.split(",").map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :update]
  before_filter :require_authorization, only: [:delete]

  def index
    if params[:tag]
      @posts = Post.tagged_with(params[:tags])
    else
      @posts = Post.all.order('created_at DESC')
      @posts = Post.includes(:user)
    end
  end

  def show
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :tag_list, :tags)
  end

  def require_authorization
    redirect_to :root unless current_user.posts.find_by_post_id(params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
 
end

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>

	<%= f.label :content %>
	<%= f.text_area :content %>

	<%= f.label :tag_list, "Tags (seperated by commas)" %>
	<%= f.text_area :tag_list %>


	<%= f.submit %>

<% end %>

app/views/posts/_post_part.html.erb
<% @posts.each do |post|%>
		<div class="well">
			<h2><%= link_to post.title, post %></h2>
				<small>Fjöldi svara: <%= post.comments.count %></small>
		
				<p><%= truncate post.content, length: 160  %> <%= link_to 'lesa meira', post %>  </p>
					<small><p>Published at <%= time_ago_in_words(post.created_at ) %> By <%= link_to post.user.name, post.user %></p></small>
			<h4>Tags</h4>
			<%= post.tag_list %>
		</div>	
	<% end %>

	<%= link_to 'Senda Spurningu', new_post_path %>
	</div>

app/views/posts/edit.html.erb
<%= render 'form' %>

<% link_to "Chancel", post_path %>

app/views/posts/index.html.erb
l<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render ('post_part') %>
    <div class="col-md-3 well" id="tag_cloud">
      <h3>tags</h3>
      <% tag_cloud Post.tag_counts, %w[css1 css2 css3 css4] do |tag, css_class| %>
      <%= link_to tag.name, tag_path(tag.id), class: css_class %>

      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="well">
			<h3><%= @post.title %></h3>
			<p><%= @post.content %></p>
		</div>	
		<div><%#= render @post.tags %></div>
		<!-- comments -->

		<h5>Fjöldi svara: <%= @post.comments.count %></h5>
			<% if signed_in? %>
			<%= render @post.comments %>

			<% else %>
			<%= "þú verður að vera með Sprettu reikning til að sjá svör" %>
			<% end %> <br>
			
		<h4> Reply to thread </h4>
			<% if signed_in? %>
			<%= render 'comments/form' %>

			<%else %>
			<%= "þú verður að vera skráður inn til að svara spurningu" %>
			<% end %> <br>

		<%= link_to "Edit", edit_post_path(@post) %> |
		<%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure you want to do this?
			"} %> |
			<%= link_to "Back", posts_path %>
	</div>
</div>	